apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod 
  spec:
    containers:
      - name: myapp-container
        image: myapp:latest
    tolerations:
      - key: "function"
        operator: "Equal"
        value: "webserver"
        effect: "NoSchedule"   